spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/app10_security_jwt01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 7497
